version: '3.8'

services:
  user-service:
    build:
      context: ../user-service
      dockerfile: Dockerfile
    container_name: user-service
    environment:
      SPRING_DATA_REDIS_HOST: keydb
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_DATASOURCE_URL: 'jdbc:postgresql://postgres:5432/apidemo-db'
    ports:
      - "8080:8080"
    networks:
      - shared-net

  notification-service:
    build:
      context: ../notification-service
      dockerfile: Dockerfile
    container_name: notification-service
    environment:
      SPRING_RABBITMQ_HOST: rabbitmq
    networks:
      - shared-net

  postgres:
    image: postgres:13.3
    container_name: postgres-lab3
    environment:
      POSTGRES_DB: "apidemo-db"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    ports:
      - "5432:5432"
    volumes:
      - .:/var/lib/postgresql/data
    restart: always
    networks:
      - shared-net

  keydb:
    image: "eqalpha/keydb:x86_64_v5.3.3"
    container_name: keydb-lab3
    command: "keydb-server /etc/keydb/redis.conf --server-threads 2"
    volumes:
      - "data:/data"
    ports:
      - "6379:6379"
    restart: unless-stopped
    networks:
      - shared-net

  rabbitmq:
    image: "rabbitmq:3-management"
    container_name: rabbitmq-archapp-lab4
    ports:
      - "5672:5672"
      - "15672:15672"
      - "15692:15692"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
      RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS: "-rabbitmq_prometheus true"
    volumes:
      - ./rabbitmq-data:/var/lib/rabbitmq
    networks:
      - shared-net

  prometheus:
    image: prom/prometheus:v2.44.0
    container_name: prometheus-archapp-lab4
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./alert_rules.yml:/etc/prometheus/alert_rules.yml
    networks:
      - shared-net
    restart: unless-stopped

  grafana:
    image: grafana/grafana
    container_name: grafana-archapp-lab4
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana-data:/var/lib/grafana
    depends_on:
      - prometheus
    networks:
      - shared-net

  alertmanager:
    image: prom/alertmanager:v0.24.0
    container_name: alertmanager-archapp-lab4
    ports:
      - "9093:9093"
    volumes:
      - ./alertmanager.yml:/etc/alertmanager/alertmanager.yml
    networks:
      - shared-net

  mailpit:
    image: axllent/mailpit
    container_name: mailpit-lab4
    networks:
      - shared-net
    ports:
      - "1025:1025"
      - "8025:8025"
    restart: unless-stopped

volumes:
  data:
    driver: local
  grafana-data:

networks:
  shared-net:
    driver: bridge