services:
  postgres:
    image: postgres:13.3
    container_name: postgres-archapp-lab3
    environment:
      POSTGRES_DB: "apidemo-db"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    ports:
      - "5432:5432"
    volumes:
      - .:/var/lib/postgresql/data
    restart: always

  keydb:
    image: "eqalpha/keydb:x86_64_v5.3.3"
    container_name: keydb-archapp-lab3
    command: "keydb-server /etc/keydb/redis.conf --server-threads 2"
    volumes:
      #      - "./redis.conf:/etc/keydb/redis.conf"
      - "data:/data"
    ports:
      - "6379:6379"
    restart: unless-stopped

  rabbitmq:
    image: "rabbitmq:3-management"
    container_name: rabbitmq-archapp-lab3
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - ./rabbitmq-data:/var/lib/rabbitmq

volumes:
  data:
    driver: local
  grafana-data:
    driver: local

networks:
  shared-net:
    driver: local